# Base image with PyTorch, CUDA 12.4, and cuDNN 9
FROM nvidia/cuda:12.4.1-cudnn-runtime-ubuntu22.04
# FROM python:3.12-slim

# Set working directory
WORKDIR /app
RUN chmod 1777 /tmp && apt-get update && apt-get install -y \
    curl wget ca-certificates \
    tar \
    &&  update-ca-certificates && rm -rf /var/lib/apt/lists/*
# Install system dependencies (including ffmpeg and other essentials)
RUN apt-get update && apt-get install -y \
    ffmpeg \
    libsndfile1 \
    python3 python3-venv python3-dev python3-pip build-essential \
    && rm -rf /var/lib/apt/lists/*

# install torch first
RUN pip3 install --no-cache-dir torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu124

# install requirements
RUN pip3 install --no-cache-dir -r requirements.txt -i https://mirrors.cloud.tencent.com/pypi/simple
COPY requirements.txt /app/
# Copy only the necessary application files
COPY *.py /app/
COPY router/*.py /app/router/

COPY *.wav /app/


# expose port
EXPOSE 12340 12341

# set start command
CMD ["python3", "main_server.py"]