# 使用官方的 Python 3.12 slim 镜像
FROM python:3.12-slim

# 设置工作目录
WORKDIR /app

# 将当前目录的内容复制到容器中
COPY odd_asr_server.py /app/
COPY trans_utils.py /app/
COPY requirements.txt /app/

# 更新包管理器并安装必要的系统依赖
RUN apt-get update && apt-get install -y \
    ffmpeg \
    libsndfile1 \
    && rm -rf /var/lib/apt/lists/*

# 安装 Python 依赖
RUN pip install --no-cache-dir -r requirements.txt

# 暴露 Flask 服务的端口
EXPOSE 12340

# 设置启动命令
CMD ["python", "odd_asr_server.py"]