# Base image with PyTorch, CUDA 12.4, and cuDNN 9
FROM nvidia/cuda:12.4.1-cudnn-runtime-ubuntu22.04
# FROM python:3.12-slim

# Set working directory
WORKDIR /app
RUN chmod 1777 /tmp && apt-get update && apt-get install -y \
    curl wget ca-certificates \
    tar \
    &&  update-ca-certificates && rm -rf /var/lib/apt/lists/*
# Install system dependencies (including ffmpeg and other essentials)
RUN apt-get update && apt-get install -y \
    ffmpeg \
    libsndfile1 \
    && rm -rf /var/lib/apt/lists/*

# Copy only the necessary application files
COPY *.py /app/
COPY router/asr_api.py /app/router/asr_api.py
COPY router/asr_front.py /app/router/asr_front.py
COPY requirements.txt /app/
COPY *.wav /app/

# update packages
RUN apt-get update && apt-get install -y \
    ffmpeg \
    libsndfile1 \
    && rm -rf /var/lib/apt/lists/*

# install torch first
RUN pip install --no-cache-dir torch torchvision torchaudio --index-url --index-url https://download.pytorch.org/whl/cu124

# install requirements
RUN pip install --no-cache-dir -r requirements.txt -i http://mirrors.cloud.tencent.com/pypi/simple

# expose port
EXPOSE 12340 12341

# set start command
CMD ["python", "main_server.py"]